// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynainbculjxxrcbvxfjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYWluYmN1bGp4eHJjYnZ4ZmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MzU5NTcsImV4cCI6MjA1NjIxMTk1N30.PY0e803dKLbJP06h5AyQwPPU2qagoAwboZMuQW1QUdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);